all:
	g++ -O2 -std=c++11 matrix_test.cc -o matrix_test

clean:
	rm matrix_test *.o


#CXX=g++
#CXXFLAGS=-O3 -std=c++11
#
#CXXFILES=$(wildcard *.cc)
#OBJS=$(subst .cc,.o,$(CXXFILES))
#
#all: matrix
#
#matrix: $(OBJS)
#	$(CXX) $(OBJS) -o $@
#
#.o:
#	$(CXX) $(CXXFLAGS) -c $<
#
#clean:
#	rm matrix *.o
